### ISSUE TITLE
Add OpenTofu Support

### ISSUE THREAD

**Issue by joeybenamy** [Snowflake-Labs/terraform-snowflake-snowpipe-aws#26]
When using the module in OpenTofu 1.8.3, we get the following error:
```
module "snowpipe" {
  source  = "Snowflake-Labs/snowpipe-aws/snowflake"
  version = "0.3.0"
  ...
}
```

Error:

> │ Error: Unsupported OpenTofu Core version
> │ 
> │   on .terraform/modules/snowpipe/versions.tf line 2, in terraform:
> │    2:   required_version = ">= 1.9.6"
> │ 
> │ Module module.snowpipe (from registry.opentofu.org/Snowflake-Labs/snowpipe-aws/snowflake) does not support OpenTofu version 1.8.3. To proceed, either choose another supported OpenTofu version
> │ or update this version constraint. Version constraints are normally set for good reason, so updating the constraint may lead to other errors or unexpected behavior.

**Comment by joscha** [comment]
This was updated via https://github.com/Snowflake-Labs/terraform-snowflake-snowpipe-aws/pull/23, specifically ebf5ba05348edf853074259a6c992f640f696186.

I bumped it to 1.9.6 because that was the latest at the time, however I can see on https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest that is supports Terraform 0.13+, so maybe we can roll this

https://github.com/Snowflake-Labs/terraform-snowflake-snowpipe-aws/blob/ca5aea23a0efcbd34ff24dcd098e66f7542c1c85/versions.tf#L2

back to `>=1.8.3`?

@sfc-gh-pkommini WDYT?

**Comment by joeybenamy** [comment]
> @joeybenamy you can use the `0.24.0` version for now, to be unblocked.

Thanks!  We ended up forking internally for now until and will revisit once Snowflake provider is in 1.0 and the module is upgraded.

**Comment by joscha** [comment]
> Thanks! We ended up forking internally for now and will revisit once the Snowflake provider is in 1.0 and the module is upgraded.

👍 
Hopefully we will get this pulled straight. Did you just reduce the requirement to `1.8.3`?
Do you have any idea if required versions for terraform and opentofu can be defined separately? I googled but seem to only find that you can't, which kind of makes sense for compatibility, but is also a bit odd.

**Comment by joeybenamy** [comment]
> > Thanks! We ended up forking internally for now and will revisit once the Snowflake provider is in 1.0 and the module is upgraded.
> 
> 👍 Hopefully we will get this pulled straight. Did you just reduce the requirement to `1.8.3`? Do you have any idea if required versions for terraform and opentofu can be defined separately? I googled but seem to only find that you can't, which kind of makes sense for compatibility, but is also a bit odd.

I don't think the version requirements can be defined separately.  We just removed the block altogether.

**Comment by sfc-gh-pkommini** [comment]
Created a new release. Let me know if you're all set.
